const supabaseUrl = 'https://qdnjwmhptgatluujxhuz.supabase.co';
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkbmp3bWhwdGdhdGx1dWp4aHV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk2MTg2NjMsImV4cCI6MjA5NTE5NDY2M30.LMEGhZZJg_EeK2i_ax8eGLpjHwnXOCYqHoh6C2XXLMg';
